// Shared sim shape maths (mw-e04.2): collision shapes, poses, closest distances and swept overlap
// tests used by melee hit volumes and, later, arrows (e05) and spells.
export {
  boxCorners,
  boxesOverlap,
  pointBoxSq,
  pointSegmentSq,
  pointTriangleSq,
  segmentBoxSq,
  segmentSegmentSq,
  segmentTriangleSq,
  triangleBoxSq,
  triangleTriangleSq,
  type Obb,
} from './distance';
export {
  boundPieces,
  boundsOverlap,
  composePose,
  IDENTITY_POSE,
  MAX_BOX_SUBSTEPS,
  obbOf,
  pieceBounds,
  pieceOf,
  piecesOverlap,
  placeShape,
  shapesOverlap,
  simplexBoxSq,
  simplexDistanceSq,
  sweepPieces,
  transformPoint,
  unionBounds,
  type BoundedPiece,
  type BoundedPieces,
  type GeomBounds,
  type GeomBox,
  type GeomCapsule,
  type GeomShape,
  type GeomSphere,
  type LocalShape,
  type Piece,
  type Pose,
  type Simplex,
} from './shapes';
export { at, IDENTITY_QUAT, mulQuat, nlerpQuat, normalizeQuat, rotate, yawQuat } from './vec';
