// The save-schema lock (mw-e30.3, backlog contract §3): forgetting a save migration must be
// impossible, not merely discouraged. Every save section's zod schema is fingerprinted (a SHA-256 of
// its JSON Schema export) and the committed lock records, per fixture revision, each section's
// version and fingerprint plus the envelope versions. A revision is one set of versions; its
// fixtures live in tests/save-fixtures/<revision>/. The check fails when a section's schema changes
// without a version bump, when versions move with no new fixture revision, or when a revision's
// fixtures are missing — each with the instructions to fix it.

import { createHash } from 'node:crypto';
import {
  SAVE_FORMAT_VERSION,
  SAVE_SCHEMA_VERSION,
  type SaveRegistry,
  type SaveSection,
} from '@game/save/format';
import { z } from 'zod';

/** One section's locked schema. */
export interface SectionLock {
  readonly version: number;
  /** `sha256:` + hex digest of the section schema's normalised JSON Schema (input side). */
  readonly fingerprint: string;
}

/** The versions and section fingerprints a build writes. */
export interface SchemaState {
  /** The save byte layout version (SAVE_FORMAT_VERSION). */
  readonly formatVersion: number;
  /** The envelope field-set version (SAVE_SCHEMA_VERSION). */
  readonly saveSchemaVersion: number;
  /** Section id → version and fingerprint. */
  readonly sections: Readonly<Record<string, SectionLock>>;
}

/** A locked schema state whose fixtures live in tests/save-fixtures/<revision>/. */
export interface SchemaRevision extends SchemaState {
  /** 1, 2, 3… in order; a new one is added whenever any version changes. */
  readonly revision: number;
}

/** The committed lock file: every revision there has ever been, oldest first. */
export interface SchemaLock {
  readonly revisions: readonly SchemaRevision[];
}

const version = z.int().positive();

const lockSchema = z.strictObject({
  $comment: z.string().optional(),
  revisions: z.array(
    z.strictObject({
      revision: version,
      formatVersion: version,
      saveSchemaVersion: version,
      sections: z.record(
        z.string(),
        z.strictObject({ version, fingerprint: z.string().regex(/^sha256:[0-9a-f]{64}$/) }),
      ),
    }),
  ),
});

/** Explains the lock file to whoever opens it. */
export const LOCK_COMMENT =
  'Generated by pnpm save:fixture (mw-e30.3). Never edit by hand: change a save section schema, bump its version, add a migration, then run pnpm save:fixture.';

/**
 * Parses lock file JSON.
 * @throws Error listing the schema issues when the lock is malformed.
 */
export function parseLock(data: unknown): SchemaLock {
  const parsed = lockSchema.safeParse(data);
  if (!parsed.success) {
    const issues = parsed.error.issues.map(
      (issue) => `${issue.path.map(String).join('.') || '(root)'}: ${issue.message}`,
    );
    throw new Error(`save schema lock is malformed: ${issues.join('; ')}`);
  }
  return { revisions: parsed.data.revisions };
}

/** Lock file text: stable key order, two-space indent, trailing newline. */
export function serializeLock(lock: SchemaLock): string {
  const revisions = lock.revisions.map(
    ({ revision, formatVersion, saveSchemaVersion, sections }) => ({
      revision,
      formatVersion,
      saveSchemaVersion,
      sections: Object.fromEntries(
        Object.keys(sections)
          .sort()
          .map((id) => [id, sections[id]]),
      ),
    }),
  );
  return `${JSON.stringify({ $comment: LOCK_COMMENT, revisions }, null, 2)}\n`;
}

/** Arrays whose order carries no meaning in JSON Schema; sorted so field reordering is not a change. */
const UNORDERED = new Set(['required', 'enum']);

function normalise(value: unknown, key?: string): unknown {
  if (Array.isArray(value)) {
    const items = value.map((item) => normalise(item));
    return key !== undefined && UNORDERED.has(key)
      ? items.sort((a, b) => (JSON.stringify(a) < JSON.stringify(b) ? -1 : 1))
      : items;
  }
  if (typeof value === 'object' && value !== null) {
    const record = value as Record<string, unknown>;
    return Object.fromEntries(
      Object.keys(record)
        .sort()
        .map((k) => [k, normalise(record[k], k)]),
    );
  }
  return value;
}

/**
 * Fingerprints a section's schema: SHA-256 of its JSON Schema export (input side, since saves store
 * input data), with object keys and order-free arrays sorted. Refinements are invisible to it; any
 * change to types, fields, optionality, enums or bounds changes it.
 * @throws Error naming the section when its schema has no JSON Schema form (z.custom, z.date…).
 */
export function fingerprintSection(section: Pick<SaveSection, 'id' | 'schema'>): string {
  let jsonSchema: unknown;
  try {
    jsonSchema = z.toJSONSchema(section.schema, { io: 'input' });
  } catch (error) {
    throw new Error(
      `save section "${section.id}" schema cannot be fingerprinted (${(error as Error).message}); use JSON-representable zod types`,
      { cause: error },
    );
  }
  const digest = createHash('sha256')
    .update(JSON.stringify(normalise(jsonSchema)))
    .digest('hex');
  return `sha256:${digest}`;
}

/** The schema state of a registry as this build defines it. */
export function schemaStateOf(registry: SaveRegistry): SchemaState {
  return {
    formatVersion: SAVE_FORMAT_VERSION,
    saveSchemaVersion: SAVE_SCHEMA_VERSION,
    sections: Object.fromEntries(
      registry.sections.map((section) => [
        section.id,
        { version: section.version, fingerprint: fingerprintSection(section) },
      ]),
    ),
  };
}

/** Why the gate failed; `kind` lets `pnpm save:fixture` tell fixable states from refusals. */
export interface LockProblem {
  /**
   * `unversioned-change`: a section schema changed but its version did not (AC-2).
   * `version-regressed`: a version went down.
   * `stale-lock`: versions changed but no fixture revision records them (AC-3).
   * `revision-order`: lock revisions are not numbered 1..N.
   * `fixtures-missing`: a revision has no fixture directory, or it is empty.
   * `unknown-fixture-dir`: a fixture directory matches no revision.
   */
  readonly kind:
    | 'unversioned-change'
    | 'version-regressed'
    | 'stale-lock'
    | 'revision-order'
    | 'fixtures-missing'
    | 'unknown-fixture-dir';
  readonly message: string;
}

/** Where fixture revisions live, relative to the repo root. */
export const SAVE_FIXTURE_DIR = 'tests/save-fixtures';

const byKey = ([a]: readonly [string, unknown], [b]: readonly [string, unknown]): number =>
  Number(a > b) - Number(a < b);

/** What changed in versions between two states, e.g. `world v1 → v2`; empty when none. */
export function versionChanges(from: SchemaState, to: SchemaState): string[] {
  const changes: string[] = [];
  if (from.formatVersion !== to.formatVersion) {
    changes.push(`format v${String(from.formatVersion)} → v${String(to.formatVersion)}`);
  }
  if (from.saveSchemaVersion !== to.saveSchemaVersion) {
    changes.push(`envelope v${String(from.saveSchemaVersion)} → v${String(to.saveSchemaVersion)}`);
  }
  for (const [id, after] of Object.entries(to.sections).sort(byKey)) {
    const before = from.sections[id];
    if (before === undefined) changes.push(`${id} added at v${String(after.version)}`);
    else if (before.version !== after.version) {
      changes.push(`${id} v${String(before.version)} → v${String(after.version)}`);
    }
  }
  for (const id of Object.keys(from.sections).sort()) {
    if (!(id in to.sections)) changes.push(`${id} removed`);
  }
  return changes;
}

function unversionedChanges(state: SchemaState, lock: SchemaLock): LockProblem[] {
  const problems: LockProblem[] = [];
  for (const [id, current] of Object.entries(state.sections)) {
    const locked = lock.revisions.find((revision) => {
      const section = revision.sections[id];
      return section?.version === current.version && section.fingerprint !== current.fingerprint;
    });
    if (locked === undefined) continue;
    const next = current.version + 1;
    problems.push({
      kind: 'unversioned-change',
      message:
        `save section "${id}" schema changed but its version is still ${String(current.version)} ` +
        `(revision ${String(locked.revision)} locked a different schema at that version). ` +
        `Saves already written at v${String(current.version)} would no longer load. ` +
        `Bump the section's version to ${String(next)}, add migrations[${String(current.version)}] ` +
        `(v${String(current.version)} → v${String(next)}) that upgrades stored data, then run ` +
        `pnpm save:fixture to commit a fixture for the new version.`,
    });
  }
  return problems;
}

function regressions(state: SchemaState, latest: SchemaRevision): LockProblem[] {
  const problems: LockProblem[] = [];
  const pairs: [string, number, number][] = [
    ['save format', state.formatVersion, latest.formatVersion],
    ['save envelope', state.saveSchemaVersion, latest.saveSchemaVersion],
    ...Object.entries(state.sections).map(([id, section]): [string, number, number] => [
      `save section "${id}"`,
      section.version,
      latest.sections[id]?.version ?? 0,
    ]),
  ];
  for (const [what, now, locked] of pairs) {
    if (now >= locked) continue;
    problems.push({
      kind: 'version-regressed',
      message: `${what} is at version ${String(now)} but revision ${String(latest.revision)} locked version ${String(locked)}; versions never go down.`,
    });
  }
  return problems;
}

/**
 * Checks a build's schema state against the committed lock and the fixture directories on disk.
 * @param fixtureDirs fixture directory name → number of fixture files in it.
 * @returns every problem found; empty when the gate passes.
 */
export function checkSchemaLock(
  state: SchemaState,
  lock: SchemaLock,
  fixtureDirs: Readonly<Record<string, number>>,
): LockProblem[] {
  const problems: LockProblem[] = [];
  if (lock.revisions.some((revision, i) => revision.revision !== i + 1)) {
    problems.push({
      kind: 'revision-order',
      message: 'save schema lock revisions must be numbered 1, 2, 3… in order.',
    });
  }
  problems.push(...unversionedChanges(state, lock));
  const latest = lock.revisions.at(-1);
  if (latest === undefined) {
    problems.push({
      kind: 'stale-lock',
      message:
        'the save schema lock has no revisions yet: run pnpm save:fixture to create revision 1.',
    });
  } else {
    problems.push(...regressions(state, latest));
    const changes = versionChanges(latest, state);
    if (changes.length > 0) {
      const next = `${SAVE_FIXTURE_DIR}/${String(latest.revision + 1)}/`;
      problems.push({
        kind: 'stale-lock',
        message:
          `save schema versions changed since revision ${String(latest.revision)} ` +
          `(${changes.join(', ')}) but no fixture revision records them. Make sure each bumped ` +
          `section has a migration for the step, then run pnpm save:fixture to commit ${next} ` +
          `and the updated lock.`,
      });
    }
  }
  for (const { revision } of lock.revisions) {
    if ((fixtureDirs[String(revision)] ?? 0) > 0) continue;
    problems.push({
      kind: 'fixtures-missing',
      message:
        `${SAVE_FIXTURE_DIR}/${String(revision)}/ has no fixtures. Fixtures are never deleted: ` +
        `restore it from git history, or for the newest revision run pnpm save:fixture.`,
    });
  }
  const known = new Set(lock.revisions.map(({ revision }) => String(revision)));
  for (const dir of Object.keys(fixtureDirs).sort()) {
    if (known.has(dir)) continue;
    problems.push({
      kind: 'unknown-fixture-dir',
      message: `${SAVE_FIXTURE_DIR}/${dir}/ is not a revision in the save schema lock; remove it or run pnpm save:fixture.`,
    });
  }
  return problems;
}

/** Whether a state is exactly the lock's newest revision (versions and fingerprints). */
export function matchesLatest(state: SchemaState, lock: SchemaLock): boolean {
  const latest = lock.revisions.at(-1);
  if (latest === undefined || versionChanges(latest, state).length > 0) return false;
  return Object.entries(state.sections).every(
    ([id, section]) => latest.sections[id]?.fingerprint === section.fingerprint,
  );
}
