// The player in the sim (mw-e02.23): spawn, mouse-look yaw and pitch and ActionFrame → controller wiring.
export {
  clampPitch,
  DEFAULT_LOOK_SETTINGS,
  installPlayer,
  KNIGHT_DODGE,
  lookTurn,
  NoPlayerStartError,
  PLAYER_LOOK_SENSITIVITY,
  PLAYER_START_TAG,
  PlayerLook,
  playerLookSystem,
  playerStart,
  spawnYaw,
  stickResponse,
  wrapYaw,
  yawForward,
  type LookInput,
  type LookSettings,
  type LookTurn,
  type PlayerCombatOptions,
  type PlayerOptions,
  type StickLookSettings,
} from './player';
