// The player in the sim (mw-e02.23): spawn, mouse-look yaw and pitch and ActionFrame → controller wiring;
// with combat, the dodge (mw-e04.8), the knight's sword and shield (mw-e04.6) and the bow (mw-e05.3).
export {
  clampPitch,
  DEFAULT_BOW_NOCK,
  DEFAULT_HEAVY_BUTTON,
  DEFAULT_PARRY_BUTTON,
  DEFAULT_LOOK_SETTINGS,
  installPlayer,
  KNIGHT_DODGE,
  KNIGHT_HEAVY_ATTACK,
  KNIGHT_LIGHT_ATTACK,
  KNIGHT_KICK,
  KNIGHT_PARRY,
  KNIGHT_RIPOSTE,
  KNIGHT_SHIELD_BASH,
  lookAim,
  lookTurn,
  NoPlayerStartError,
  PLAYER_FALL_RESET_MARGIN,
  PLAYER_LOOK_SENSITIVITY,
  PLAYER_START_TAG,
  PlayerLook,
  playerLookSystem,
  playerFallRecoverySystem,
  playerSpawn,
  playerStart,
  restrainMovement,
  spawnYaw,
  stickResponse,
  ViewAnchor,
  wrapYaw,
  yawForward,
  type BowNock,
  type LookInput,
  type LookSettings,
  type LookTurn,
  type PlayerBowOptions,
  type PlayerClimbOptions,
  type PlayerCombatOptions,
  type PlayerLedgeOptions,
  type PlayerMeleeOptions,
  type PlayerOptions,
  type StickLookSettings,
} from './player';
