// Public API of the content layer (mw-e00.18): schemas + data files, validated at load into a typed,
// deeply frozen catalogue. src/sim may import these only as types (`import type`).
// Not exported here, by design: fs-sources.ts (Node only), testing.ts (Vitest only) and
// json-schema.ts (build-time tooling; keeps zod's JSON Schema generator out of the game bundle).

/** Layer marker, checked by the alias smoke test. */
export const layer = 'content' as const;

export { CONTENT_ID_PATTERN, ContentRef, contentId, ref, serializeContent } from './schema.ts';
export {
  ContentLoadError,
  dottedPath,
  jsonPointer,
  loadContent,
  type Catalogue,
  type ContentIssue,
  type ContentSchemas,
  type ContentCheck,
  type ContentSource,
  type EntryOf,
  type LoadedEntry,
  type Frozen,
} from './loader.ts';
export {
  ANIM_MARKER_KINDS,
  animClipSchema,
  type AnimClipDef,
  type AnimClipDefInput,
  type AnimMarkerKind,
} from './types/anim-clip.ts';
export {
  ANIM_ACTION_PHASES,
  ANIM_ACTION_VERBS,
  ANIM_HIT_DIRECTIONS,
  ANIM_CONDITION_OPS,
  ANIM_LAYER_MODES,
  ANIM_LOCOMOTION_STATES,
  ANIM_PARAMETERS,
  ANIM_PARAMETER_NAMES,
  ANIM_RESTART_FADE,
  animGraphSchema,
  motionClips,
  type AnimBoneDef,
  type AnimConditionDef,
  type AnimConditionOp,
  type AnimGraphDef,
  type AnimGraphDefInput,
  type AnimLayerDef,
  type AnimLayerMode,
  type AnimMotionDef,
  type AnimParameterName,
  type AnimParameterSpec,
  type AnimStateDef,
  type AnimTransitionDef,
} from './types/anim-graph.ts';
export {
  ANIM_MAX_MARKER_DRIFT_TICKS,
  ANIM_SIM_HZ,
  animMarkerDrift,
  checkAnimation,
  type AnimMarkerDrift,
  type DriftClip,
  type DriftMove,
} from './anim-checks.ts';
export {
  ATTACK_KINDS,
  ATTACK_SCHEMA_VERSION,
  AttackCompileError,
  TARGET_STANCES,
  attackSchema,
  compileAttack,
  compileAttacks,
  type AttackDef,
  type AttackDefInput,
  type AttackEntry,
  type AttackKind,
  type AttackTable,
  type RuntimeAttack,
  type TargetStance,
} from './types/attack.ts';
export {
  PLAYER_CAMERA_ID,
  cameraSchema,
  cameraTuningSchema,
  type CameraDef,
  type CameraDefInput,
  type CameraTuning,
} from './types/camera.ts';
export {
  MAX_COYOTE_MS,
  MAX_JUMP_BUFFER_MS,
  PLAYER_CONTROLLER_ID,
  controllerSchema,
  controllerTuningSchema,
  gaitTuningSchema,
  type ControllerDef,
  type ControllerDefInput,
  type ControllerTuning,
  type GaitTuning,
} from './types/controller.ts';
export {
  CREATURE_FAMILIES,
  CREATURE_SCHEMA_VERSION,
  PERSONALITY_TRAITS,
  SIZE_CLASSES,
  STANCES,
  creatureSchema,
  type CreatureDef,
  type CreatureDefInput,
} from './types/creature.ts';
export {
  CUE_EVENTS,
  CUE_EVENT_NAMES,
  CUE_FACT_KINDS,
  CUE_PLACEHOLDER,
  checkCueRule,
  cueEventSpec,
  cuePlaceholders,
  cueRuleBaseFields,
  type CueEventName,
  type CueEventSpec,
  type CueFactKind,
  type CueRuleShape,
} from './cue-events.ts';
export {
  CUE_DEDUPE_MS,
  CUE_TEMPLATE_PATTERN,
  cueRuleSchema,
  cueSheetSchema,
  type CueRuleDef,
  type CueSheetDef,
  type CueSheetDefInput,
} from './types/cue-sheet.ts';
export {
  FACT_KEY_PATTERN,
  FACT_PERSISTENCE,
  FACT_TEMPLATE_PATTERN,
  FACT_VALUE_TYPES,
  factSchema,
  factTemplateOf,
  type FactDef,
  type FactGroup,
  type FactGroupInput,
} from './types/fact.ts';
export {
  CONDITION_MAX_DEPTH,
  CONDITION_OPERATORS,
  COUNT_PATTERN,
  conditionSchema,
  namedConditionSchema,
  type Condition,
  type CountCondition,
  type FactCondition,
  type NamedCondition,
  type NamedConditionInput,
} from './types/condition.ts';
export {
  CONDITION_USAGES,
  checkConditions,
  conditionProblems,
  type ConditionProblem,
  type ConditionUsage,
} from './condition-checks.ts';
export {
  FACT_USAGES,
  checkFacts,
  factIndex,
  lookupFact,
  type FactIndex,
  type FactUsage,
} from './fact-checks.ts';
export {
  PLAYER_FACTION_ID,
  UNALIGNED_FACTION,
  factionSchema,
  type FactionDef,
  type FactionDefInput,
} from './types/faction.ts';
export {
  KIT_PURPOSES,
  KIT_SHAPES,
  kitPartSchema,
  kitSchema,
  vec3Schema,
  type KitDef,
  type KitDefInput,
  type KitPartDef,
  type KitPurpose,
  type KitShape,
} from './types/kit.ts';
export {
  SCENE_SNAP_STEP,
  SCENE_YAWS,
  scenePlacementSchema,
  sceneSchema,
  sceneSpawnSchema,
  type SceneDef,
  type SceneDefInput,
  type ScenePlacementDef,
  type SceneSpawnDef,
  type SceneYaw,
} from './types/scene.ts';
export {
  DAMAGE_TYPES,
  HIT_DIRECTIONS,
  HIT_REACTION_DEFAULTS,
  HIT_REACTION_KINDS,
  HIT_REACTION_TIERS,
  hitReactionsSchema,
  MAX_RESISTANCE,
  poiseRegenSchema,
  resistancesSchema,
  type DamageTypeName,
  type HitDirection,
  type HitReactionKind,
  type HitReactionTier,
} from './types/damage.ts';
export {
  AREA_REQUIREMENTS,
  GAITS,
  LINK_REQUIREMENTS,
  LOCOMOTION_MODES,
  LocomotionResolutionError,
  NAV_AREAS,
  NAV_BITS,
  NAV_CAPABILITIES,
  NAV_LINK_KINDS,
  canEnterArea,
  canTraverseLink,
  capabilityMask,
  creatureLocomotionSchema,
  deriveNavAgent,
  locomotionProfileSchema,
  locomotionSchema,
  navMask,
  resolveLocomotion,
  type CreatureLocomotion,
  type Gait,
  type LocomotionDef,
  type LocomotionDefInput,
  type LocomotionMode,
  type LocomotionProfile,
  type LocomotionProfileLookup,
  type NavAgent,
  type NavArea,
  type NavCapability,
  type NavLink,
  type NavLinkKind,
} from './types/locomotion.ts';
export {
  FOOTSTEP_LOUDNESS_RANGE,
  IMPACT_SOUND_PATTERN,
  BURNT_DESTROYED,
  burntMaterials,
  burntStateSchema,
  materialPresets,
  materialPropertiesSchema,
  materialSchema,
  type MaterialDef,
  type MaterialDefInput,
  type MaterialProperties,
} from './types/material.ts';
export {
  ANIM_ID_PATTERN,
  AUDIO_CUE_PATTERN,
  CANCEL_TARGETS,
  MOTION_DIRECTIONS,
  MOVE_SCHEMA_VERSION,
  MOVE_VERBS,
  REACH_CLASSES,
  SWING_KINDS,
  VFX_CUE_PATTERN,
  compileMove,
  compileMoves,
  damageTemplateSchema,
  moveSchema,
  moveWarnings,
  type CancelTarget,
  type DamageTemplate,
  type KnownCues,
  type MoveDef,
  type MoveDefInput,
  type MoveEntry,
  type MoveTable,
  type MoveVerb,
  type MotionDirection,
  type MoveWarning,
  type ReachClass,
  type RuntimeCancelWindow,
  type RuntimeMotion,
  type RuntimeMove,
  type SwingKind,
  type TickRange,
} from './types/move.ts';
export {
  SOCKET_ROTATION_TOLERANCE,
  checkSocketTracks,
  compileSocketTrack,
  compileSocketTracks,
  socketTrackSchema,
  type RuntimeSocketPose,
  type RuntimeSocketTrack,
  type SocketTrackDef,
  type SocketTrackDefInput,
  type SocketTrackEntry,
  type SocketTrackTable,
} from './types/socket-track.ts';
export {
  COMBAT_SANDBOX_ID,
  SANDBOX_HIT_REGIONS,
  compileSandbox,
  sandboxSchema,
  type RuntimeSandbox,
  type RuntimeSandboxAttacker,
  type RuntimeSandboxDummy,
  type SandboxDef,
  type SandboxDefInput,
  type SandboxEntry,
  type SandboxHitRegion,
} from './types/sandbox.ts';
export {
  KNIGHT_SHIELD_ID,
  compileShield,
  shieldSchema,
  type RuntimeShield,
  type ShieldDef,
  type ShieldDefInput,
  type ShieldEntry,
} from './types/shield.ts';
export {
  SPECIAL_SENSE_CHANNELS,
  SenseResolutionError,
  creatureSensesSchema,
  resolveSenses,
  senseProfileSchema,
  senseSchema,
  type CreatureSenses,
  type SenseDef,
  type SenseDefInput,
  type SenseProfile,
  type SenseProfileLookup,
  type SpecialSenseChannel,
} from './types/sense.ts';
export {
  PREDICATE_OPS,
  REGISTERED_KINDS,
  SIGNAL_ELEMENTS,
  SIGNAL_NODE_KINDS,
  SIGNAL_RECEIVERS,
  signalGraphSchema,
  signalPorts,
  type SignalGraphEntry,
  type SignalGraphEntryInput,
  type SignalGraphNode,
} from './types/signal-graph.ts';
export {
  AOE_ORIGINS,
  DISPLACE_MODES,
  FORCE_MODES,
  LIGHT_ATTACHMENTS,
  MAX_SPELL_TIER,
  NOISE_PHASES,
  SPELL_DELIVERIES,
  SPELL_EFFECT_OPS,
  SPELL_SCHEMA_VERSION,
  SPELL_SCHOOLS,
  SPELL_STIMULUS_ELEMENTS,
  spellSchema,
  type SpellDefinition,
  type SpellDefinitionInput,
  type SpellDelivery,
  type SpellDeliveryKind,
  type SpellEffect,
  type SpellEffectOpName,
  type SpellEntry,
  type SpellSchool,
  type SpellStimulusElement,
} from './types/spell.ts';
export {
  HEX_COLOUR_PATTERN,
  VFX_BLEND_MODES,
  VFX_QUALITY_TIERS,
  VFX_TEXTURE_PATTERN,
  vfxEffectSchema,
  vfxEmitterSchema,
  type VfxBlendMode,
  type VfxColourCurve,
  type VfxEffectDef,
  type VfxEffectDefInput,
  type VfxEmitterDef,
  type VfxQualityTier,
  type VfxScalarCurve,
} from './types/vfx-effect.ts';
export { canonicalJson, fnv1a64 } from './hash.ts';
export {
  toPropertyInit,
  worldPropertiesSchema,
  type Present,
  type WorldPropertiesData,
  type WorldPropertiesInit,
} from './world-properties.ts';
export {
  contentChecks,
  contentTypes,
  type ContentType,
  type ContentTypes,
  type GameContent,
  type GameEntry,
} from './registry.ts';
export { GAME_CONTENT_ROOT, gameContentSources, loadGameContent } from './game-content.ts';
