// The closed, versioned set of world properties (mw-e03.1). Interactions come from properties
// (flammable, wet, conductive…), never from pairs of object types, so every system — fire, water,
// stealth, physics, AI — reads and writes this one vocabulary. This module is the single sim-side
// definition of each property: its value type, range, unit, default and meaning. The content layer
// mirrors it as a zod schema (src/content/world-properties.ts); tests/contracts keeps the two equal.
// Adding, removing or changing a property is a schema change: bump WORLD_PROPERTIES_VERSION (save
// migrations, e30, key off it). Version 2 (mw-e03.31) added the properties other epics assumed —
// magic, combat, stealth, traps, ropes — under one camelCase spelling each; the canonical table is
// docs/design/world-properties.md (generated by `pnpm content:docs`).

/**
 * Bumped whenever a property is added, removed, renamed or changes type or range.
 * v1: the mw-e03.1 set. v2: mw-e03.31 additions (additive only: a v1 save loads unchanged).
 */
export const WORLD_PROPERTIES_VERSION = 2;

/** A light source's output. Colour is a render concern and lives outside the sim. */
export interface LightEmission {
  /** Light output in sim light units (0 = dark; a torch is about 100). */
  readonly intensity: number;
  /** Distance in metres beyond which the source contributes no light. */
  readonly radius: number;
}

/** Surface hardness grades: footstep loudness and whether arrows stick (soft, medium, hard). */
export const SURFACE_HARDNESS = ['soft', 'medium', 'hard'] as const;
/** One surface hardness grade. */
export type SurfaceHardness = (typeof SURFACE_HARDNESS)[number];

/** Kinds of hit a breakable object has a toughness against. */
export const BREAK_TYPES = ['blunt', 'slash', 'pierce', 'force'] as const;
/** One kind of hit (`force` is a raw force stimulus: a shockwave, a falling boulder). */
export type BreakType = (typeof BREAK_TYPES)[number];

/**
 * Energy of a single hit of each kind that breaks a `breakable` object, J. A kind left out never
 * breaks it (an old wall has blunt and force toughness only, so a sword never cuts it down).
 */
export type Toughness = Readonly<Partial<Record<BreakType, number>>>;

/** Every world property and its value type. Absent on an entity = the property's default. */
export interface WorldPropertyValues {
  /** Material preset id (e03-material-presets supplies the per-material defaults). */
  material: string;
  /** Current temperature, °C. */
  temperature: number;
  /** Fire can ignite it (see `isFlammableNow` for whether it can right now). */
  flammable: boolean;
  /** Temperature at which it ignites, °C. */
  ignitionPoint: number;
  /** Seconds of burning left before the fuel is spent. */
  fuel: number;
  /** On fire right now. */
  burning: boolean;
  /** How soaked it is: 0 dry … 1 saturated. */
  wetness: number;
  /** Frozen solid (ice, or an object encased in it). */
  frozen: boolean;
  /** Temperature at or below which it freezes, °C. */
  freezePoint: number;
  /** Conducts electric charge. */
  conductive: boolean;
  /** Stored electric charge, sim charge units (0 = neutral). */
  charge: number;
  /** Mass, kg. */
  weight: number;
  /** Breaks when a single impact delivers at least this much energy, J. */
  fragile: number;
  /** Structural hit points; at 0 it is destroyed or collapses. */
  hp: number;
  /** Density, kg/m³: below water's 1000 it floats (buoyancy). */
  density: number;
  /** Climbing grade: 1 easy (ladder, ivy), 2 needs stamina (rough stone), 3 needs skill or a tool. */
  climbable: number;
  /** Can be picked up and carried. */
  liftable: boolean;
  /** Can be pushed or dragged. */
  pushable: boolean;
  /** An actor can hide in or behind it. */
  hideable: boolean;
  /** Mirror-like: light beams and bolts bounce off it by the surface normal (e03 light beams). */
  reflective: boolean;
  /** Light and sight pass through it (glass, water, ice). */
  transparent: boolean;
  /** Fully blocks light and sight. Neither this nor transparent = partial cover (foliage, cloth). */
  opaque: boolean;
  /** Emits light. */
  lightEmitter: LightEmission;
  /** Fraction of sound it absorbs: 0 none … 1 all. */
  soundDamping: number;
  /** Surface friction coefficient (ice ≈ 0.05, stone ≈ 0.6, rubber ≈ 1). */
  friction: number;
  /** Fraction of impact energy it absorbs (straw, cushions): 0 none … 1 all. */
  impactAbsorb: number;
  /** Ownership tag (faction or owner id): taking or breaking an owned object can be a crime. */
  owner: string;

  // v2 (mw-e03.31)
  /** A liquid (water, oil): it pours, puddles and can have a `waterSurface`. */
  liquid: boolean;
  /** A gas (volume) that ignites, flaring or exploding, when fire reaches it. */
  flammableGas: boolean;
  /** A fire or light source that water, force or an interaction can put out (and relight). */
  extinguishable: boolean;
  /** The top surface of a body of liquid: cold freezes it into walkable ice; it can be waded. */
  waterSurface: boolean;
  /** Force of a single push, blast or quake that shakes it loose so it topples or falls, J. */
  unstable: number;
  /** Hangs from its `support`; falls when the support breaks, burns or is cut. */
  suspended: boolean;
  /** Entity a `suspended` object hangs from (0 = none). */
  support: number;
  /** Damage breaks it: a hit of one kind at or above its `toughness` for that kind. */
  breakable: boolean;
  /** Per kind of hit, the single-hit energy that breaks a `breakable` object, J. */
  toughness: Toughness;
  /** A shield bash or kick shoves it, or breaks it when also breakable. */
  bashable: boolean;
  /** Slash or pierce damage severs it (ropes, cords, nets). */
  cuttable: boolean;
  /** A projectile hit with at least this impulse fires its signal (bells, targets), N·s. */
  shootable: number;
  /** Rope arrows and hooks embed in it (wood, earth). */
  softAnchor: boolean;
  /** Surface hardness: footstep loudness and whether arrows stick or ricochet. */
  surfaceHardness: SurfaceHardness;
  /** A mechanism input that fires when its stored charge reaches this, charge units. */
  chargeActivated: number;
  /** A mechanism input that fires when light on it reaches this, light units. */
  lightActivated: number;
  /** Not perceivable or targetable until revealed (secret doors, hidden stashes). */
  hidden: boolean;
  /** Armed: interacting with it triggers its `trap` unless it is disarmed first. */
  trapped: boolean;
  /** Trap definition a `trapped` object triggers (`none` = no trap). */
  trap: string;
  /** Marker: it holds items (the e18 container component has the contents). */
  container: boolean;
  /** Inert skeletal or corpse remains that summoning can raise. */
  remains: boolean;
  /** Multiplier on the noise its wearer makes (armour, bells); an actor's is the product of its equipment's. */
  noiseMultiplier: number;
}

/** Name of a world property. */
export type WorldPropertyKey = keyof WorldPropertyValues;

interface SpecBase<T> {
  /** Effective value when an entity doesn't have the property. */
  readonly default: T;
  /** One-line meaning, used in docs and editor tooltips. */
  readonly doc: string;
}

/** Inclusive numeric range (every property number is finite). */
export interface NumberRange {
  readonly min: number;
  readonly max: number;
  /** Whole numbers only. */
  readonly integer?: true;
  /** Display unit, '' when unitless. */
  readonly unit: string;
}

export interface NumberSpec extends SpecBase<number>, NumberRange {
  readonly type: 'number';
}
export interface BooleanSpec extends SpecBase<boolean> {
  readonly type: 'boolean';
}
/** A lowercase kebab-case id (same format as content ids). */
export interface IdSpec extends SpecBase<string> {
  readonly type: 'id';
}
/** One of a fixed list of strings, e.g. `surfaceHardness`. */
export interface EnumSpec<T extends string> extends SpecBase<T> {
  readonly type: 'enum';
  readonly values: readonly T[];
}
/** A flat record of numbers, e.g. `lightEmitter`. */
export interface RecordSpec<T> extends SpecBase<T> {
  readonly type: 'record';
  readonly fields: { readonly [F in keyof T]-?: NumberRange };
  /** Fields may be left out (a missing field means the property's own documented fallback). */
  readonly partial?: true;
}

/** The spec a property with value type `T` has. */
export type PropertySpec<T> = [T] extends [number]
  ? NumberSpec
  : [T] extends [boolean]
    ? BooleanSpec
    : [T] extends [string]
      ? string extends T
        ? IdSpec
        : EnumSpec<T>
      : RecordSpec<T>;

/** Any property's spec, for code that handles every kind. */
export type AnyPropertySpec =
  | NumberSpec
  | BooleanSpec
  | IdSpec
  | EnumSpec<string>
  | (SpecBase<unknown> & {
      readonly type: 'record';
      readonly fields: Readonly<Record<string, NumberRange>>;
      readonly partial?: true;
    });

/** Lowercase kebab-case, e.g. `dry-wood` (mirrors the content id format). */
export const PROPERTY_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const ABSOLUTE_ZERO = -273.15;
/** Hotter than anything the game simulates; a larger value is a bug, not a hot fire. */
const MAX_TEMPERATURE = 10_000;

const celsius = (fallback: number, doc: string): NumberSpec => ({
  type: 'number',
  min: ABSOLUTE_ZERO,
  max: MAX_TEMPERATURE,
  unit: '°C',
  default: fallback,
  doc,
});
const unit01 = (doc: string): NumberSpec => ({
  type: 'number',
  min: 0,
  max: 1,
  unit: '',
  default: 0,
  doc,
});
const flag = (doc: string): BooleanSpec => ({ type: 'boolean', default: false, doc });
/**
 * A trigger threshold: the property's presence makes the object react once an input reaches the
 * value. The default (the range's maximum) sits beyond anything the input can reach, so an object
 * without the property never triggers.
 */
const threshold = (max: number, unit: string, doc: string): NumberSpec => ({
  type: 'number',
  min: 0,
  max,
  unit,
  default: max,
  doc,
});
/** Energies in J: 10⁹ is far beyond any hit, blast or fall in the game (effectively never). */
const MAX_ENERGY = 1_000_000_000;

/** Every property's spec. Keys are the snapshot and data-file names: never rename one. */
export const WORLD_PROPERTY_SPECS: {
  readonly [K in WorldPropertyKey]: PropertySpec<WorldPropertyValues[K]>;
} = {
  material: { type: 'id', default: 'generic', doc: 'Material preset id.' },
  temperature: celsius(20, 'Current temperature.'),
  flammable: flag('Fire can ignite it.'),
  ignitionPoint: celsius(300, 'Temperature at which it ignites.'),
  fuel: {
    type: 'number',
    min: 0,
    max: 86_400,
    unit: 's',
    default: 0,
    doc: 'Seconds of burning left.',
  },
  burning: flag('On fire right now.'),
  wetness: unit01('How soaked it is (0 dry, 1 saturated).'),
  frozen: flag('Frozen solid.'),
  freezePoint: celsius(0, 'Temperature at or below which it freezes.'),
  conductive: flag('Conducts electric charge.'),
  charge: {
    type: 'number',
    min: 0,
    max: 1_000_000,
    unit: 'charge',
    default: 0,
    doc: 'Stored electric charge.',
  },
  weight: { type: 'number', min: 0, max: 1_000_000, unit: 'kg', default: 1, doc: 'Mass.' },
  fragile: threshold(
    MAX_ENERGY,
    'J',
    'Impact energy of any kind that breaks it (the default is effectively unbreakable).',
  ),
  hp: {
    type: 'number',
    min: 0,
    max: 1_000_000,
    unit: 'hp',
    default: 100,
    doc: 'Structural hit points.',
  },
  density: {
    type: 'number',
    min: 0.01,
    max: 100_000,
    unit: 'kg/m³',
    default: 1000,
    doc: 'Density; below 1000 it floats in water.',
  },
  climbable: {
    type: 'number',
    min: 1,
    max: 3,
    integer: true,
    unit: 'grade',
    default: 1,
    doc: 'Climbing grade: 1 easy, 2 needs stamina, 3 needs skill or a tool.',
  },
  liftable: flag('Can be picked up and carried.'),
  pushable: flag('Can be pushed or dragged.'),
  hideable: flag('An actor can hide in or behind it.'),
  reflective: flag('Mirror-like: light beams and bolts bounce off it by the surface normal.'),
  transparent: flag('Light and sight pass through it.'),
  opaque: flag('Fully blocks light and sight.'),
  lightEmitter: {
    type: 'record',
    fields: {
      intensity: { min: 0, max: 100_000, unit: 'light' },
      radius: { min: 0, max: 100, unit: 'm' },
    },
    default: { intensity: 0, radius: 0 },
    doc: 'Emits light of this intensity out to this radius.',
  },
  soundDamping: unit01('Fraction of sound it absorbs.'),
  friction: {
    type: 'number',
    min: 0,
    max: 2,
    unit: '',
    default: 0.6,
    doc: 'Surface friction coefficient.',
  },
  impactAbsorb: unit01('Fraction of impact energy it absorbs.'),
  owner: { type: 'id', default: 'unowned', doc: 'Ownership tag (faction or owner id).' },
  liquid: flag('A liquid: it pours, puddles and can have a water surface.'),
  flammableGas: flag('A gas that ignites (flares or explodes) when fire reaches it.'),
  extinguishable: flag('A fire or light source that water, force or an interaction puts out.'),
  waterSurface: flag('Top surface of a body of liquid: cold freezes it into walkable ice.'),
  unstable: threshold(MAX_ENERGY, 'J', 'Force of one push, blast or quake that topples it.'),
  suspended: flag('Hangs from its support; falls when the support breaks, burns or is cut.'),
  support: {
    type: 'number',
    min: 0,
    max: Number.MAX_SAFE_INTEGER,
    integer: true,
    unit: 'entity',
    default: 0,
    doc: 'Entity a suspended object hangs from (0 = none).',
  },
  breakable: flag('A single hit at or above its toughness for that kind of hit breaks it.'),
  toughness: {
    type: 'record',
    fields: {
      blunt: { min: 0, max: MAX_ENERGY, unit: 'J' },
      slash: { min: 0, max: MAX_ENERGY, unit: 'J' },
      pierce: { min: 0, max: MAX_ENERGY, unit: 'J' },
      force: { min: 0, max: MAX_ENERGY, unit: 'J' },
    },
    partial: true,
    default: {},
    doc: 'Single-hit energy per kind of hit that breaks a breakable object (a kind left out never does).',
  },
  bashable: flag('A shield bash or kick shoves it (or breaks it when breakable).'),
  cuttable: flag('Slash or pierce damage severs it.'),
  shootable: threshold(1_000_000, 'N·s', 'Projectile impulse that fires its signal.'),
  softAnchor: flag('Rope arrows and hooks embed in it.'),
  surfaceHardness: {
    type: 'enum',
    values: SURFACE_HARDNESS,
    default: 'medium',
    doc: 'Footstep loudness and whether arrows stick (soft, medium) or ricochet (hard).',
  },
  chargeActivated: threshold(MAX_ENERGY, 'charge', 'Stored charge at which the mechanism fires.'),
  lightActivated: threshold(MAX_ENERGY, 'light', 'Light level on it at which the mechanism fires.'),
  hidden: flag('Not perceivable or targetable until revealed.'),
  trapped: flag('Interacting with it triggers its trap unless disarmed first.'),
  trap: { type: 'id', default: 'none', doc: 'Trap definition a trapped object triggers.' },
  container: flag('Holds items (contents live in the e18 container component).'),
  remains: flag('Inert skeletal or corpse remains that summoning can raise.'),
  noiseMultiplier: {
    type: 'number',
    min: 0.2,
    max: 3,
    unit: '×',
    default: 1,
    doc: "Multiplier on its wearer's noise; an actor's is the product of its equipment's.",
  },
};

/** Every property name, in code-unit order (the canonical order for docs and iteration). */
export const WORLD_PROPERTY_KEYS: readonly WorldPropertyKey[] = Object.freeze(
  (Object.keys(WORLD_PROPERTY_SPECS) as WorldPropertyKey[]).sort(),
);

/** Whether `key` names a world property. */
export function isWorldPropertyKey(key: string): key is WorldPropertyKey {
  return Object.hasOwn(WORLD_PROPERTY_SPECS, key);
}

function checkNumber(range: NumberRange, value: unknown): string | undefined {
  if (typeof value !== 'number' || !Number.isFinite(value)) return 'must be a finite number';
  if (value < range.min) return `must be ≥ ${String(range.min)}, got ${String(value)}`;
  if (value > range.max) return `must be ≤ ${String(range.max)}, got ${String(value)}`;
  if (range.integer === true && !Number.isInteger(value)) {
    return `must be a whole number, got ${String(value)}`;
  }
  return undefined;
}

function checkRecord(
  fields: Readonly<Record<string, NumberRange>>,
  partial: boolean,
  value: unknown,
) {
  if (
    typeof value !== 'object' ||
    value === null ||
    Object.getPrototypeOf(value) !== Object.prototype
  ) {
    return 'must be a plain object';
  }
  const extra = Object.keys(value).find((name) => !Object.hasOwn(fields, name));
  if (extra !== undefined) return `has unknown field "${extra}"`;
  for (const [name, range] of Object.entries(fields)) {
    if (partial && !Object.hasOwn(value, name)) continue;
    const problem = checkNumber(range, (value as Record<string, unknown>)[name]);
    if (problem !== undefined) return `.${name} ${problem}`;
  }
  return undefined;
}

/**
 * Why `value` is not a valid value of property `key` (e.g. `"wetness must be ≤ 1, got 1.4"`), or
 * undefined when it is valid. Accepts untyped input (restored saves, tools).
 */
export function validateProperty(key: WorldPropertyKey, value: unknown): string | undefined {
  const spec: AnyPropertySpec = WORLD_PROPERTY_SPECS[key];
  let problem: string | undefined;
  switch (spec.type) {
    case 'number':
      problem = checkNumber(spec, value);
      break;
    case 'boolean':
      problem = typeof value === 'boolean' ? undefined : 'must be true or false';
      break;
    case 'id':
      problem =
        typeof value === 'string' && PROPERTY_ID_PATTERN.test(value)
          ? undefined
          : 'must be a lowercase kebab-case id';
      break;
    case 'enum':
      problem = (spec.values as readonly unknown[]).includes(value)
        ? undefined
        : `must be one of ${spec.values.join(', ')}`;
      break;
    case 'record':
      problem = checkRecord(spec.fields, spec.partial === true, value);
      break;
  }
  return problem === undefined ? undefined : `${key} ${problem}`;
}

/** Throws a RangeError unless `value` is a valid value of property `key`. */
export function assertProperty<K extends WorldPropertyKey>(
  key: K,
  value: unknown,
): asserts value is WorldPropertyValues[K] {
  const problem = validateProperty(key, value);
  if (problem !== undefined) throw new RangeError(problem);
}
